### ISSUE TITLE
ffmpeg server 1.1.1.5 error

### ISSUE THREAD

**Issue by temp042** [PauloCesar0073/GCT_Courses#1]
Erro ao abrir o executavel do servidor ffmpeg

Traceback (most recent call last):
  File "ffmpegWEB.py", line 426, in <module>
  File "ffmpegWEB.py", line 112, in __init__
  File "tkinter\__init__.py", line 2150, in wm_iconbitmap
_tkinter.TclError: bitmap "C:\Users\paulo\Documents\GitHub\GET_Course_FONT\SERVER\icons.ico" not defined

**Comment by PauloCesar0073** [comment]
- [x] bug corrigido !   obrigado pelo feedback.
